version: '3'
services:
  client:
    build: 
      context: ./client/
      dockerfile: Dockerfile.dev
    command: npm run serve
    environment:
      NODE_ENV: develop
      PORT: 8080
    volumes:
      - ./client:/etc/app
    ports: 
      - 8080:8080
  controller:
    build: 
      context: ./controller/
      dockerfile: Dockerfile.dev
    command: python ./src/control.py
    environment:
      PORT: 8090
      REDIS_URL: "redis://redis:6379"
      PYTHON_ENV: "testing"
    volumes:
      - ./controller:/etc/app
    ports: 
      - 8090:8090
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    links:
      - redis
    expose:
      - 8000
    ports: 
      - 8000:8000
    volumes:
      - ./api:/etc/app
    environment:
      NODE_ENV: develop
      REDIS_URL: "redis://redis:6379"
      PORT: 8000
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
volumes:
  db_data:
