version: '3'
services:
  client:
    build: 
      context: ./client/
      dockerfile: Dockerfile.dev
    command: npm run serve
    environment:
      NODE_ENV: develop
      PORT: 8080
    volumes:
      - ./client:/etc/app
    ports: 
      - 8080:8080
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile.dev
    links:
      - redis
    expose:
      - 8000
    environment:
      NODE_ENV: develop
      PORT: 8000
  redis:
    image: redis
    container_name: cache 
    expose:
      - 6379
volumes:
  db_data:
