FROM python:3.7

WORKDIR /tmp/
ADD requirements.testing.txt /tmp/
RUN pip install --upgrade pip && \
    pip install -r requirements.testing.txt

WORKDIR /etc/app
ADD src/ ./

CMD ["python", "./src/control.py"]